"""allow event without support

Revision ID: 007c0a6febd2
Revises: c45aab3d0038
Create Date: 2026-07-31 10:44:28.156066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007c0a6febd2'
down_revision: Union[str, Sequence[str], None] = 'c45aab3d0038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'support_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'support_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
